[2020-12-08 14:17:28] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App\Exceptions\Response' not found in C:\xampp\htdocs\lumen\ddsbe2\app\Exceptions\Handler.php:50
Stack trace:
#0 C:\xampp\htdocs\lumen\ddsbe2\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(105): App\Exceptions\Handler->render(Object(Laravel\Lumen\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#1 C:\xampp\htdocs\lumen\ddsbe2\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(173): Laravel\Lumen\Application->sendExceptionToHandler(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#2 C:\xampp\htdocs\lumen\ddsbe2\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#3 C:\xampp\htdocs\lumen\ddsbe2\public\index.php(28): Laravel\Lumen\Application->run()
#4 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Exceptions\\Response' not found at C:\\xampp\\htdocs\\lumen\\ddsbe2\\app\\Exceptions\\Handler.php:50)
[stacktrace]
#0 C:\\xampp\\htdocs\\lumen\\ddsbe2\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RegistersExceptionHandlers.php(105): App\\Exceptions\\Handler->render(Object(Laravel\\Lumen\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#1 C:\\xampp\\htdocs\\lumen\\ddsbe2\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(173): Laravel\\Lumen\\Application->sendExceptionToHandler(Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#2 C:\\xampp\\htdocs\\lumen\\ddsbe2\\vendor\\laravel\\lumen-framework\\src\\Concerns\\RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)
#3 C:\\xampp\\htdocs\\lumen\\ddsbe2\\public\\index.php(28): Laravel\\Lumen\\Application->run()
#4 {main}
"} 
